### ISSUE TITLE
Error when turning off "on_off" heaters

### ISSUE THREAD

**Issue by the-programmer** [vindaalex/multizone-thermostat#17]
Hi,

I would like to let you know that I got the following error when trying to turn off a "on_off" heater.
"argument of type 'nonetype' is not iterable"

This is on the following line:
https://github.com/vindaalex/multizone-thermostat/blob/master/custom_components/multizone_thermostat/hvac_setting.py#L622

I fixed this for now by having `check_window_open` return false.

**Comment by vindaalex** [comment]
Thank you for the bug report. I have not been able to reproduce the error with my current configs. Could you provide me your thermostat config as well and/or error you receive?

**Comment by the-programmer** [comment]
My config is as follows:
configuration.yaml
```
[...]
climate: !include yaml_configs/climate.yaml
[...]
```

yaml_configs/climate.yaml
```
[...]
- platform: multizone_thermostat
  name: Slaapkamer 1
  unique_id: thermostat_bedroom_1
  sensor: sensor.mod_ai_temp_bedroom1
  filter_mode: 2
  initial_hvac_mode: "heat"
  initial_preset_mode: "none"
  precision: 0.1
  heat:
    entity_id: input_boolean.mod_o_heating_bedroom1_wanted
    min_target_temp: 15
    max_target_temp: 24
    initial_target_temp: 20
    away_temp: 16
    #proportional_mode:
    #  control_interval:
    #    seconds: 30
    #  pwm:
    #    seconds: 3600
    #  PID_mode:
    #    kp: 20
    #    ki: 0.005
    #    kd: -25000
    on_off_mode:
      hysteresis_on: 0.2
      hysteresis_off: 0.2
      min_cycle_duration:
        minutes: 5
      control_interval:
        minutes: 1
[...]
```
Note: I was switching away from proportional_mode as a trial.
