### ISSUE TITLE
set_preset_mode service not working properly

### ISSUE THREAD

**Issue by stomko11** [vindaalex/multizone-thermostat#28]
I am trying to automate few things. I managed to use service `multizone_thermostat.set_preset_mode` to set the preset on the master thermostat, and that gets synced to all the satellites.
However i am not having luck with `heat` or `off`. Example I used:

```
service: multizone_thermostat.set_preset_mode
data:
  hvac_mode: heat
  preset_mode: none
  entity_id: climate.master
```
or
```
service: multizone_thermostat.set_preset_mode
data:
  hvac_mode: off
  preset_mode: none
  entity_id: climate.master
```

When running `off` against master, none of satellite thermostats turns off. Also, if I turn one of them off, and then run the `heat` against master, no action is taken, and the one that was off stays off. Only changing presets works OK. Is this desired behavior and this service shall be used only for presets? For on/off, should I keep using generic climate service? Thanks

**Comment by vindaalex** [comment]
Calling `set_preset_mode` with below would change the preset for the `hvac mode` "off". It will not change the `hvac mode` itself. 
```
service: multizone_thermostat.set_preset_mode
data:
  hvac_mode: off
  preset_mode: none
  entity_id: climate.master
```

To change the `hvac mode` you could use `climate.set_hvac_mode`
```
service: climate.set_hvac_mode
data:
  entity_id: climate.master
  hvac_mode: heat
```

For the master the `hvac_mode` differs in behaviour compared to the `set_preset`. `set_preset` forwards the preset to all satellites while `set_hvac_mode` would change the master `hvac mode` and:
- when changed to "off": change the satellite operation mode to individual (as if it are independent thermostats)
- when changed to "heat" (or "cool"): it changes the operation mode of the satellites to be controlled by the master.
